### ISSUE TITLE
Cannot set stabilizer on water source

### ISSUE THREAD

**Issue by uhloin** [Sirttas/ElementalCraft#112]
Other source types are ok.
Also did not found a way to remove stabilizer to move to another source.

**Comment by Sirttas** [comment]
What version are you on?

**Comment by uhloin** [comment]
elementalcraft-1.19.2-5.4.6.jar

**Comment by Sirttas** [comment]
Can you make sure the source is analyzed? It is required to be stabilized or displaced (I'm adding an error message for the next version).

Second point: stab shouldn't be moved around from source to source, since it grant an increase recovery I don't want people moving the stab once a source recovered to on that is starting its recovery.

**Comment by uhloin** [comment]
I checked, after analyze I can set stabilizer. It is OK with error message or/and warning it in book.

About recovery - it'is most boring part of mod and source movement is second boring. I would make them very cheap and easy-get since start of game.
